//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqModel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.108;Initial Catalog=ZY_ZhuiSu;Persist Security Info=True;Us" +
            "er ID=sa;Password=lbs~123;MultipleActiveResultSets=True;Application Name=EntityF" +
            "ramework")]
        public string ZY_ZhuiSuConnectionString {
            get {
                return ((string)(this["ZY_ZhuiSuConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:mgdj8tjei6.database.chinacloudapi.cn,1433;Initial Catalog=ZY_Zhui" +
            "Su;User ID=zhiyun@mgdj8tjei6")]
        public string ZY_ZhuiSuConnectionString1 {
            get {
                return ((string)(this["ZY_ZhuiSuConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.108;Initial Catalog=ZY_ZhuiSu;Persist Security Info=True;Us" +
            "er ID=sa;MultipleActiveResultSets=True;Application Name=EntityFramework")]
        public string ZY_ZhuiSuConnectionString2 {
            get {
                return ((string)(this["ZY_ZhuiSuConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:mgdj8tjei6.database.chinacloudapi.cn,1433;Initial Catalog=ZY_Zhui" +
            "Su;Persist Security Info=True;User ID=zhiyun@mgdj8tjei6")]
        public string ZY_ZhuiSuConnectionString3 {
            get {
                return ((string)(this["ZY_ZhuiSuConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=127.0.0.1;Initial Catalog=ZY_ZhuiSu;Integrated Security=True")]
        public string ZY_ZhuiSuConnectionString4 {
            get {
                return ((string)(this["ZY_ZhuiSuConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=121.42.12.155;Initial Catalog=ZhuiSu_Single;User ID=ZhuiSu_SingleAdmi" +
            "n")]
        public string ZhuiSu_SingleConnectionString {
            get {
                return ((string)(this["ZhuiSu_SingleConnectionString"]));
            }
        }
    }
}
